on:
  pull_request:
  workflow_call:

name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run:  npm install
      - name: build
        run:  npm run build
      - name: test
        run:  npm run test
      - name: lint
        run:  npm run lint:check
