on:
  push:
    branches:
      - master

name: CI
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: decentraland/gh-action-release@0.3.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

  build:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: get latest release and export as GITHUB_REF
        run:  echo "GIT_TAG=$(git tag | sort -V | tail -1)" > $GITHUB_ENV
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run:  npm install
      - name: lint
        run:  npm run lint:check
      - name: test
        run:  npm run test
      - name: build
        run:  npm run build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
